# Recall Memory System - Windows Deployment Script
# Usage: .\scripts\deploy.ps1 [-OllamaHost "http://192.168.50.62:11434"]
#
# Prerequisites:
#   - Docker Desktop installed and running
#   - Ollama running with bge-large model

param(
    [string]$OllamaHost = "http://192.168.50.62:11434",
    [int]$RecallPort = 8200
)

$ErrorActionPreference = "Stop"

function Log { param([string]$msg) Write-Host "[RECALL] $msg" -ForegroundColor Green }
function Warn { param([string]$msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Err { param([string]$msg) Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

$ProjectDir = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not $ProjectDir) { $ProjectDir = Get-Location }

Log "Recall Memory System Deployment"
Log "================================"
Log "Ollama Host: $OllamaHost"
Log "Recall Port: $RecallPort"
Log "Project Dir: $ProjectDir"
Write-Host ""

# Check Docker
Log "Checking prerequisites..."
try {
    docker version | Out-Null
} catch {
    Err "Docker is not running. Please start Docker Desktop."
}

# Check Ollama
Log "Checking Ollama connectivity..."
try {
    $response = Invoke-RestMethod -Uri "$OllamaHost/api/tags" -TimeoutSec 5 -ErrorAction SilentlyContinue
    Log "Ollama is reachable"
} catch {
    Warn "Cannot reach Ollama at $OllamaHost"
    $continue = Read-Host "Continue anyway? (y/N)"
    if ($continue -ne 'y') { exit 1 }
}

# Check/pull model
Log "Checking for bge-large embedding model..."
try {
    $models = Invoke-RestMethod -Uri "$OllamaHost/api/tags" -ErrorAction SilentlyContinue
    $hasBge = $models.models | Where-Object { $_.name -like "*bge-large*" }
    if ($hasBge) {
        Log "bge-large model found"
    } else {
        Log "Pulling bge-large model..."
        Invoke-RestMethod -Uri "$OllamaHost/api/pull" -Method Post -Body '{"name":"bge-large"}' -ErrorAction SilentlyContinue
    }
} catch {
    Warn "Could not check/pull model - will retry on first use"
}

# Navigate to project
Set-Location $ProjectDir

# Create .env if missing
if (-not (Test-Path ".env")) {
    Log "Creating .env file..."
    @"
# Recall Memory System Configuration
# Generated by deploy.ps1 on $(Get-Date)

RECALL_OLLAMA_HOST=$OllamaHost
RECALL_API_PORT=$RecallPort
RECALL_DEBUG=false

NEO4J_AUTH=neo4j/recallmemory
POSTGRES_PASSWORD=recallmemory
"@ | Out-File -FilePath ".env" -Encoding utf8
    Log "Created .env file"
}

# Stop existing
Log "Stopping existing containers..."
docker compose down 2>$null

# Build and start
Log "Building containers..."
docker compose build

Log "Starting Recall stack..."
docker compose up -d

# Wait for health
Log "Waiting for services to initialize..."
$maxWait = 60
$waited = 0

while ($waited -lt $maxWait) {
    try {
        $health = Invoke-RestMethod -Uri "http://localhost:$RecallPort/health" -TimeoutSec 2 -ErrorAction SilentlyContinue
        if ($health.status -eq "healthy") { break }
    } catch {}
    Write-Host "." -NoNewline
    Start-Sleep -Seconds 2
    $waited += 2
}
Write-Host ""

if ($health.status -eq "healthy") {
    Log "All services are healthy!"
} else {
    Warn "Services may still be starting. Check: http://localhost:$RecallPort/health"
}

# Warm up model
Log "Warming up embedding model..."
try {
    Invoke-RestMethod -Uri "$OllamaHost/api/embeddings" -Method Post -Body '{"model":"bge-large","prompt":"warmup"}' -ErrorAction SilentlyContinue | Out-Null
} catch {}

# Done
Write-Host ""
Log "=========================================="
Log "Recall Memory System Deployed!"
Log "=========================================="
Write-Host ""
Log "API:     http://localhost:$RecallPort"
Log "Health:  http://localhost:$RecallPort/health"
Log "Stats:   http://localhost:$RecallPort/stats"
Write-Host ""
