#!/bin/bash
# Recall Memory System - One-Click Deployment
# Usage: ./scripts/deploy.sh [OLLAMA_HOST]
#
# Prerequisites:
#   - Docker & Docker Compose installed
#   - Ollama running with qwen3-embedding:0.6b model (or specify host)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() { echo -e "${GREEN}[RECALL]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Configuration
OLLAMA_HOST="${1:-http://localhost:11434}"
RECALL_PORT="${RECALL_PORT:-8200}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

log "Recall Memory System Deployment"
log "================================"
log "Ollama Host: $OLLAMA_HOST"
log "Recall Port: $RECALL_PORT"
log "Project Dir: $PROJECT_DIR"
echo ""

# Check prerequisites
log "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker first."
fi

if ! command -v docker compose &> /dev/null && ! command -v docker-compose &> /dev/null; then
    error "Docker Compose is not installed. Please install Docker Compose first."
fi

# Determine compose command
if docker compose version &> /dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
else
    COMPOSE_CMD="docker-compose"
fi

log "Using: $COMPOSE_CMD"

# Check Ollama connectivity
log "Checking Ollama connectivity..."
if curl -s --connect-timeout 5 "$OLLAMA_HOST/api/tags" > /dev/null 2>&1; then
    log "Ollama is reachable at $OLLAMA_HOST"
else
    warn "Cannot reach Ollama at $OLLAMA_HOST"
    warn "Make sure Ollama is running with: OLLAMA_HOST=0.0.0.0:11434 ollama serve"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Check/pull embedding model
log "Checking for qwen3-embedding:0.6b embedding model..."
MODELS=$(curl -s "$OLLAMA_HOST/api/tags" 2>/dev/null || echo '{"models":[]}')
if echo "$MODELS" | grep -q "qwen3-embedding"; then
    log "qwen3-embedding model found"
else
    log "Pulling qwen3-embedding:0.6b model (this may take a few minutes)..."
    curl -X POST "$OLLAMA_HOST/api/pull" -d '{"name":"qwen3-embedding:0.6b"}' || warn "Could not pull model - will retry on first use"
fi

# Create .env file if it doesn't exist
cd "$PROJECT_DIR"

if [ ! -f .env ]; then
    log "Creating .env file..."
    cat > .env << EOF
# Recall Memory System Configuration
# Generated by deploy.sh on $(date)

# External Services
RECALL_OLLAMA_HOST=$OLLAMA_HOST

# API Configuration
RECALL_API_PORT=$RECALL_PORT
RECALL_DEBUG=false

# Security (change these in production!)
NEO4J_AUTH=neo4j/recallmemory
POSTGRES_PASSWORD=recallmemory
EOF
    log "Created .env file - edit for production use"
else
    log "Using existing .env file"
fi

# Stop any existing containers
log "Stopping existing containers..."
$COMPOSE_CMD down 2>/dev/null || true

# Pull/build images
log "Building containers..."
$COMPOSE_CMD build

# Start the stack
log "Starting Recall stack..."
$COMPOSE_CMD up -d

# Wait for services to be healthy
log "Waiting for services to initialize..."
MAX_WAIT=60
WAITED=0

while [ $WAITED -lt $MAX_WAIT ]; do
    HEALTH=$(curl -s "http://localhost:$RECALL_PORT/health" 2>/dev/null || echo '{"status":"starting"}')
    STATUS=$(echo "$HEALTH" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)

    if [ "$STATUS" = "healthy" ]; then
        break
    fi

    echo -n "."
    sleep 2
    WAITED=$((WAITED + 2))
done
echo ""

if [ "$STATUS" = "healthy" ]; then
    log "All services are healthy!"
else
    warn "Services may still be starting. Check with: curl http://localhost:$RECALL_PORT/health"
fi

# Warm up embedding model
log "Warming up embedding model..."
curl -s -X POST "$OLLAMA_HOST/api/embed" \
    -d '{"model":"qwen3-embedding:0.6b","input":"warmup"}' > /dev/null 2>&1 || true

# Final status
echo ""
log "=========================================="
log "Recall Memory System Deployed!"
log "=========================================="
log ""
log "API:     http://localhost:$RECALL_PORT"
log "Health:  http://localhost:$RECALL_PORT/health"
log "Stats:   http://localhost:$RECALL_PORT/stats"
log ""
log "Quick test:"
log "  curl -X POST http://localhost:$RECALL_PORT/memory/store \\"
log "    -H 'Content-Type: application/json' \\"
log "    -d '{\"content\":\"Test memory\",\"memory_type\":\"semantic\"}'"
log ""
log "View logs:"
log "  $COMPOSE_CMD logs -f api"
log ""
