"""
Marathon corpus — 200+ memories across 8 subdomains, 40 search queries,
20 conversation pairs for session worker.
"""

# 8 subdomain suffixes appended to sim-marathon-{run_id}-
SUBDOMAINS = [
    "infra", "code-patterns", "debug-notes", "architecture",
    "devops", "security", "performance", "data-eng",
]

# ~25 memories per subdomain = 200 total
MEMORIES: dict[str, list[dict]] = {
    "infra": [
        {"content": "Proxmox backup schedule runs daily at 2am to local NAS via PBS.", "importance": 0.7, "type": "semantic"},
        {"content": "CasaOS VM allocated 16GB RAM and 8 vCPUs for Docker workloads.", "importance": 0.6, "type": "semantic"},
        {"content": "Gluetun VPN container routes all *arr stack traffic through Mullvad.", "importance": 0.7, "type": "semantic"},
        {"content": "UPS provides 45 minutes of backup power for the homelab rack.", "importance": 0.5, "type": "semantic"},
        {"content": "Proxmox host uses ZFS mirror for boot drives with weekly scrub.", "importance": 0.6, "type": "semantic"},
        {"content": "DNS resolution goes through OPNsense Unbound with DNSSEC enabled.", "importance": 0.5, "type": "semantic"},
        {"content": "Home Assistant runs on the local network with Zigbee2MQTT for device control.", "importance": 0.4, "type": "semantic"},
        {"content": "WireGuard tunnel between OPNsense and VPS provides secure remote access.", "importance": 0.7, "type": "semantic"},
        {"content": "MinIO S3-compatible storage runs on CasaOS for backup and media.", "importance": 0.4, "type": "semantic"},
        {"content": "Tailscale mesh VPN connects all devices with MagicDNS resolution.", "importance": 0.6, "type": "semantic"},
        {"content": "Proxmox cluster quorum requires at least 3 nodes for HA failover.", "importance": 0.5, "type": "semantic"},
        {"content": "VLAN 50 is the IoT network, isolated from the trusted VLAN 10.", "importance": 0.6, "type": "semantic"},
        {"content": "NFS share at /mnt/data is exported to Docker host for persistent volumes.", "importance": 0.5, "type": "semantic"},
        {"content": "Caddy reverse proxy handles automatic HTTPS with Let's Encrypt certificates.", "importance": 0.6, "type": "semantic"},
        {"content": "Prometheus node_exporter runs on each host for hardware monitoring.", "importance": 0.4, "type": "semantic"},
        {"content": "Grafana dashboards configured for Proxmox, Docker, and network metrics.", "importance": 0.4, "type": "semantic"},
        {"content": "SMART monitoring enabled on all NAS drives with email alerts.", "importance": 0.5, "type": "semantic"},
        {"content": "Cloudflare Tunnel used as fallback when WireGuard VPN is down.", "importance": 0.5, "type": "semantic"},
        {"content": "Docker networks use bridge mode with explicit subnet assignments per stack.", "importance": 0.4, "type": "semantic"},
        {"content": "Portainer agent deployed for remote Docker management from web UI.", "importance": 0.3, "type": "semantic"},
        {"content": "SSH key authentication enforced; password auth disabled on all servers.", "importance": 0.8, "type": "semantic"},
        {"content": "Cron job rotates logs weekly and compresses them with gzip.", "importance": 0.3, "type": "semantic"},
        {"content": "GPU passthrough on Proxmox requires IOMMU groups and vfio-pci driver.", "importance": 0.7, "type": "semantic"},
        {"content": "The RTX 3090 operates in a dedicated Ollama VM with 24GB VRAM.", "importance": 0.7, "type": "semantic"},
        {"content": "Wake-on-LAN configured for the Proxmox host via OPNsense automation.", "importance": 0.4, "type": "semantic"},
    ],
    "code-patterns": [
        {"content": "Use structlog for all Python logging with JSON output in production.", "importance": 0.6, "type": "semantic"},
        {"content": "FastAPI route handlers should use Depends() for authentication injection.", "importance": 0.7, "type": "semantic"},
        {"content": "Pydantic models with Field() validators prevent invalid API inputs.", "importance": 0.6, "type": "semantic"},
        {"content": "asyncpg connections should use get_postgres_store() singleton pattern.", "importance": 0.5, "type": "semantic"},
        {"content": "Background tasks in FastAPI should be fire-and-forget with error logging.", "importance": 0.5, "type": "semantic"},
        {"content": "Redis keys follow recall:namespace:id pattern for organized key management.", "importance": 0.4, "type": "semantic"},
        {"content": "All Cypher queries must use $param syntax, never f-string interpolation.", "importance": 0.8, "type": "semantic"},
        {"content": "Content dedup uses SHA-256 hash stored in both Qdrant and Neo4j.", "importance": 0.5, "type": "semantic"},
        {"content": "Rate limiting uses slowapi with 'request: Request' as first parameter.", "importance": 0.5, "type": "semantic"},
        {"content": "Type hints required on all function signatures in the codebase.", "importance": 0.4, "type": "semantic"},
        {"content": "Dataclasses used for internal models; Pydantic for API boundary models.", "importance": 0.5, "type": "semantic"},
        {"content": "Abstract base classes define storage interfaces for Qdrant, Neo4j, Redis.", "importance": 0.5, "type": "semantic"},
        {"content": "Context managers used for database transactions to ensure rollback on error.", "importance": 0.6, "type": "semantic"},
        {"content": "Retry decorator with exponential backoff for external service calls.", "importance": 0.6, "type": "semantic"},
        {"content": "Feature flags stored in Redis for runtime toggling without restart.", "importance": 0.4, "type": "semantic"},
        {"content": "API versioning via URL prefix /v1/ to support backwards compatibility.", "importance": 0.5, "type": "semantic"},
        {"content": "Dependency injection via FastAPI Depends() for testable service layers.", "importance": 0.6, "type": "semantic"},
        {"content": "Builder pattern used for complex query construction in retrieval pipeline.", "importance": 0.5, "type": "semantic"},
        {"content": "Event sourcing pattern in audit log captures all state mutations.", "importance": 0.6, "type": "semantic"},
        {"content": "Circuit breaker wraps Ollama calls to prevent cascade failures.", "importance": 0.7, "type": "semantic"},
        {"content": "Repository pattern separates data access from business logic.", "importance": 0.5, "type": "semantic"},
        {"content": "Middleware chain: CORS → auth → rate limit → request ID → handler.", "importance": 0.5, "type": "semantic"},
        {"content": "Enum classes define valid states for memory types, durability tiers.", "importance": 0.4, "type": "semantic"},
        {"content": "Factory functions create singleton instances of storage backends.", "importance": 0.5, "type": "semantic"},
        {"content": "Structured error responses include request_id for debugging traceability.", "importance": 0.5, "type": "semantic"},
    ],
    "debug-notes": [
        {"content": "When Qdrant returns 'wrong input' error, the ID is not a valid UUID.", "importance": 0.3, "type": "episodic"},
        {"content": "Neo4j connection timeout usually means the container hasn't finished starting.", "importance": 0.4, "type": "episodic"},
        {"content": "Ollama returns empty JSON when think mode conflicts with format: json.", "importance": 0.7, "type": "episodic"},
        {"content": "SSE stream tests hang with httpx unless using client.stream() context.", "importance": 0.5, "type": "episodic"},
        {"content": "Docker logs show 'exec format error' when building ARM image on x86.", "importance": 0.3, "type": "episodic"},
        {"content": "Python output buffering causes missed logs; use line_buffering=True.", "importance": 0.4, "type": "episodic"},
        {"content": "JSONL export endpoint returns newline-delimited JSON, not a JSON array.", "importance": 0.4, "type": "episodic"},
        {"content": "qwen3:14b needs think: false API param to produce clean JSON output.", "importance": 0.6, "type": "episodic"},
        {"content": "Scroll_all() must be used for decay/consolidation instead of biased search.", "importance": 0.8, "type": "episodic"},
        {"content": "Session current_task can be None; always guard with (s.get('current_task') or '').", "importance": 0.3, "type": "episodic"},
        {"content": "httpx raises ConnectError, not ConnectionError, when the server is down.", "importance": 0.4, "type": "episodic"},
        {"content": "asyncio.gather with return_exceptions=True prevents one failure from killing all.", "importance": 0.5, "type": "episodic"},
        {"content": "Qdrant DatetimeRange goes in range= parameter, not datetime_range=.", "importance": 0.5, "type": "episodic"},
        {"content": "Neo4j integer overflow when passing Python int > 2^63-1 as Cypher parameter.", "importance": 0.4, "type": "episodic"},
        {"content": "Redis SCAN cursor must be treated as opaque string, not parsed as integer.", "importance": 0.3, "type": "episodic"},
        {"content": "FastAPI TestClient does not run startup events by default; use lifespan.", "importance": 0.5, "type": "episodic"},
        {"content": "Pydantic v2 model_dump() replaces .dict() and supports mode='json'.", "importance": 0.4, "type": "episodic"},
        {"content": "Docker compose healthcheck must use CMD-SHELL for pipe operators to work.", "importance": 0.3, "type": "episodic"},
        {"content": "aiohttp session must be closed explicitly or used as async context manager.", "importance": 0.4, "type": "episodic"},
        {"content": "StaticFiles mount returns 307 redirect; tests need follow_redirects=True.", "importance": 0.4, "type": "episodic"},
        {"content": "Background task exceptions are silently swallowed unless wrapped in try/except.", "importance": 0.5, "type": "episodic"},
        {"content": "asyncpg requires explicit type casts for jsonb columns: $1::jsonb.", "importance": 0.4, "type": "episodic"},
        {"content": "Qdrant scroll with offset requires the last seen point ID, not a numeric offset.", "importance": 0.4, "type": "episodic"},
        {"content": "Neo4j MERGE creates duplicate nodes if label casing differs between queries.", "importance": 0.5, "type": "episodic"},
        {"content": "Python 3.12+ allows type[X] syntax instead of Type[X] from typing.", "importance": 0.3, "type": "episodic"},
    ],
    "architecture": [
        {"content": "Recall uses a 5-stage retrieval pipeline: embed, search, graph expand, rerank, deduplicate.", "importance": 0.8, "type": "semantic"},
        {"content": "Memory importance decays on a logarithmic curve with configurable half-life.", "importance": 0.7, "type": "semantic"},
        {"content": "Neo4j stores relationship graphs; Qdrant stores vectors; Redis caches hot data.", "importance": 0.8, "type": "semantic"},
        {"content": "Signal detection runs as a background worker, not inline with the API request.", "importance": 0.6, "type": "semantic"},
        {"content": "Consolidation merges semantically similar memories using LLM-generated summaries.", "importance": 0.7, "type": "semantic"},
        {"content": "The ML reranker uses logistic regression with 11 features for relevance scoring.", "importance": 0.7, "type": "semantic"},
        {"content": "Spreading activation replaces flat BFS for graph-based memory expansion.", "importance": 0.6, "type": "semantic"},
        {"content": "Inhibition stage penalizes contradicting memories found via CONTRADICTS edges.", "importance": 0.5, "type": "semantic"},
        {"content": "Sub-embeddings store individual facts extracted from memories for fine-grained search.", "importance": 0.5, "type": "semantic"},
        {"content": "Health dashboard computes population balance, graph cohesion, and conflict detection.", "importance": 0.5, "type": "semantic"},
        {"content": "Document ingestion pipeline: parse → chunk → LLM extract → embed → store.", "importance": 0.6, "type": "semantic"},
        {"content": "Anti-pattern collection is separate from main memories to avoid polluting search.", "importance": 0.5, "type": "semantic"},
        {"content": "Feedback loop adjusts importance based on whether retrieved memories were useful.", "importance": 0.7, "type": "semantic"},
        {"content": "Co-retrieval tracking strengthens Neo4j edges between memories fetched together.", "importance": 0.5, "type": "semantic"},
        {"content": "Three search layers: browse (summaries), query (full), timeline (chronological).", "importance": 0.6, "type": "semantic"},
        {"content": "SSE event stream pushes real-time updates to the dashboard for live monitoring.", "importance": 0.4, "type": "semantic"},
        {"content": "Domain normalization maps aliases to canonical domains for consistent organization.", "importance": 0.5, "type": "semantic"},
        {"content": "Auto-linker creates RELATED_TO edges between semantically similar memories.", "importance": 0.5, "type": "semantic"},
        {"content": "Rate limiting is per-endpoint-class: search, ingest, admin, default buckets.", "importance": 0.5, "type": "semantic"},
        {"content": "Audit log in Postgres captures all mutations with actor, action, and details.", "importance": 0.6, "type": "semantic"},
        {"content": "Memory pinning prevents decay and is stored as keyword index in Qdrant.", "importance": 0.5, "type": "semantic"},
        {"content": "Durability tiers: ephemeral decays normally, durable at 0.15x, permanent is immune.", "importance": 0.6, "type": "semantic"},
        {"content": "Reranker weights stored in Redis and loaded at startup for zero-sklearn inference.", "importance": 0.6, "type": "semantic"},
        {"content": "Observer hook extracts facts from file edits and stores them automatically.", "importance": 0.5, "type": "semantic"},
        {"content": "Session lifecycle: start → ingest turns → detect signals → approve/reject → end.", "importance": 0.6, "type": "semantic"},
    ],
    "devops": [
        {"content": "Docker Compose on CasaOS should use 'docker compose' not docker-compose.", "importance": 0.5, "type": "semantic"},
        {"content": "Volume-mounted ./src:/app/src means restart picks up code changes instantly.", "importance": 0.7, "type": "semantic"},
        {"content": "SCP individual files then docker compose restart api worker for deployment.", "importance": 0.6, "type": "semantic"},
        {"content": "Port binding changes require docker compose down && docker compose up -d.", "importance": 0.6, "type": "semantic"},
        {"content": "New pip dependencies require full image rebuild with docker compose build.", "importance": 0.5, "type": "semantic"},
        {"content": "Container logs rotated with max-size 10m and max-file 3 in compose logging.", "importance": 0.4, "type": "semantic"},
        {"content": "Docker build cache should be pruned monthly with docker builder prune.", "importance": 0.3, "type": "semantic"},
        {"content": "Health checks in compose use curl to /health endpoint with 30s interval.", "importance": 0.5, "type": "semantic"},
        {"content": "Docker secrets should be used instead of environment variables for passwords.", "importance": 0.6, "type": "semantic"},
        {"content": "Multi-stage Dockerfile reduces image size from 1.2GB to 350MB.", "importance": 0.5, "type": "semantic"},
        {"content": "GitHub Actions CI runs pytest on PR and builds Docker image on merge to main.", "importance": 0.5, "type": "semantic"},
        {"content": "Docker Compose profiles separate dev (hot reload) from prod (gunicorn).", "importance": 0.4, "type": "semantic"},
        {"content": "Watchtower monitors Docker Hub for image updates and auto-pulls new versions.", "importance": 0.4, "type": "semantic"},
        {"content": "Alpine-based images have musl libc issues with some Python packages.", "importance": 0.5, "type": "semantic"},
        {"content": "Docker network inspect shows container IPs for debugging connectivity.", "importance": 0.3, "type": "semantic"},
        {"content": "Compose depends_on only waits for container start, not readiness.", "importance": 0.5, "type": "semantic"},
        {"content": "Named volumes persist data across container recreations; bind mounts don't.", "importance": 0.4, "type": "semantic"},
        {"content": "Docker Compose override files layer additional config for local development.", "importance": 0.3, "type": "semantic"},
        {"content": "systemd service unit ensures Docker containers restart on host reboot.", "importance": 0.5, "type": "semantic"},
        {"content": "Container resource limits set with deploy.resources.limits in compose.", "importance": 0.4, "type": "semantic"},
        {"content": "Docker BuildKit enabled by default in recent versions for better caching.", "importance": 0.3, "type": "semantic"},
        {"content": "Hadolint checks Dockerfile best practices as part of CI pipeline.", "importance": 0.3, "type": "semantic"},
        {"content": "Docker Compose watch mode enables live sync without manual restart.", "importance": 0.4, "type": "semantic"},
        {"content": "Container timezone set via TZ environment variable, not host mount.", "importance": 0.3, "type": "semantic"},
        {"content": "Trivy scans Docker images for known CVEs before deployment.", "importance": 0.5, "type": "semantic"},
    ],
    "security": [
        {"content": "API keys use rc_ prefix and are stored as bcrypt hashes in PostgreSQL.", "importance": 0.7, "type": "semantic"},
        {"content": "CORS configured to allow only specific origins, not wildcard in production.", "importance": 0.6, "type": "semantic"},
        {"content": "Rate limiting prevents brute-force attacks on authentication endpoints.", "importance": 0.7, "type": "semantic"},
        {"content": "Input validation via Pydantic ensures no SQL injection through API params.", "importance": 0.8, "type": "semantic"},
        {"content": "Error responses sanitized to never expose stack traces or internal paths.", "importance": 0.6, "type": "semantic"},
        {"content": "JWT tokens expire after 15 minutes with refresh token rotation.", "importance": 0.6, "type": "semantic"},
        {"content": "Helmet middleware sets security headers: X-Frame-Options, CSP, HSTS.", "importance": 0.5, "type": "semantic"},
        {"content": "Secrets loaded from environment variables, never hardcoded in source.", "importance": 0.8, "type": "semantic"},
        {"content": "Database credentials rotated quarterly and stored in Docker secrets.", "importance": 0.6, "type": "semantic"},
        {"content": "Audit log records all authentication events for forensic analysis.", "importance": 0.6, "type": "semantic"},
        {"content": "Network segmentation: databases only accessible from application VLAN.", "importance": 0.7, "type": "semantic"},
        {"content": "fail2ban monitors SSH and API endpoints for brute-force patterns.", "importance": 0.5, "type": "semantic"},
        {"content": "TLS 1.3 enforced on all external endpoints via reverse proxy.", "importance": 0.6, "type": "semantic"},
        {"content": "Content-Security-Policy blocks inline scripts to prevent XSS attacks.", "importance": 0.5, "type": "semantic"},
        {"content": "OAuth2 PKCE flow used for browser-based authentication to prevent interception.", "importance": 0.5, "type": "semantic"},
        {"content": "Service accounts have least-privilege access to only required resources.", "importance": 0.6, "type": "semantic"},
        {"content": "Webhook signatures verified using HMAC-SHA256 to prevent spoofing.", "importance": 0.5, "type": "semantic"},
        {"content": "Redis AUTH enabled with random 64-char password in production.", "importance": 0.6, "type": "semantic"},
        {"content": "Neo4j browser interface disabled in production to reduce attack surface.", "importance": 0.4, "type": "semantic"},
        {"content": "Dependency audit runs weekly via pip-audit and npm audit in CI.", "importance": 0.5, "type": "semantic"},
        {"content": "Docker socket not exposed to containers to prevent escape attacks.", "importance": 0.7, "type": "semantic"},
        {"content": "Backup encryption uses AES-256-GCM with key stored in hardware token.", "importance": 0.6, "type": "semantic"},
        {"content": "API rate limits per user prevent single-user resource exhaustion.", "importance": 0.5, "type": "semantic"},
        {"content": "Parameterized queries used everywhere to prevent SQL injection.", "importance": 0.8, "type": "semantic"},
        {"content": "File upload validation checks MIME type, size, and content signature.", "importance": 0.6, "type": "semantic"},
    ],
    "performance": [
        {"content": "Qdrant HNSW index with ef=128 provides sub-50ms vector search at 10K scale.", "importance": 0.6, "type": "semantic"},
        {"content": "Redis caching reduces Qdrant search calls by 40% for repeated queries.", "importance": 0.6, "type": "semantic"},
        {"content": "Connection pooling in asyncpg limits to 20 connections to prevent exhaustion.", "importance": 0.5, "type": "semantic"},
        {"content": "Batch embedding calls reduce Ollama round-trips from N to 1 per operation.", "importance": 0.6, "type": "semantic"},
        {"content": "Gzip compression on API responses reduces bandwidth by 60% for large payloads.", "importance": 0.4, "type": "semantic"},
        {"content": "Neo4j query plan analysis revealed missing index on content_hash property.", "importance": 0.5, "type": "semantic"},
        {"content": "uvicorn workers set to CPU count for optimal request parallelism.", "importance": 0.4, "type": "semantic"},
        {"content": "Lazy loading of storage backends avoids startup latency for unused services.", "importance": 0.4, "type": "semantic"},
        {"content": "Pagination with cursor-based scrolling prevents memory spikes on large results.", "importance": 0.5, "type": "semantic"},
        {"content": "Background task queue prevents long-running LLM calls from blocking API.", "importance": 0.7, "type": "semantic"},
        {"content": "Semaphore limits concurrent Ollama calls to prevent GPU saturation.", "importance": 0.7, "type": "semantic"},
        {"content": "Redis pipeline batches multiple commands into single round-trip.", "importance": 0.4, "type": "semantic"},
        {"content": "Qdrant payload indexing on domain and memory_type speeds filtered search.", "importance": 0.5, "type": "semantic"},
        {"content": "Embedding cache in Redis stores vectors for 24h to avoid recomputation.", "importance": 0.5, "type": "semantic"},
        {"content": "P95 latency target is 500ms for search endpoints under normal load.", "importance": 0.5, "type": "semantic"},
        {"content": "Memory-mapped files used for large embedding model loading.", "importance": 0.4, "type": "semantic"},
        {"content": "Async generators stream large result sets without buffering everything.", "importance": 0.5, "type": "semantic"},
        {"content": "Database connection health checks run every 30s to detect stale connections.", "importance": 0.4, "type": "semantic"},
        {"content": "JSON serialization uses orjson for 3x throughput over standard json module.", "importance": 0.4, "type": "semantic"},
        {"content": "CDN caching for static dashboard assets with 1-hour TTL and ETag.", "importance": 0.3, "type": "semantic"},
        {"content": "Neo4j relationship traversal limited to 3 hops to prevent query explosion.", "importance": 0.5, "type": "semantic"},
        {"content": "Materialized view in Postgres caches domain statistics for /stats endpoint.", "importance": 0.4, "type": "semantic"},
        {"content": "Write-ahead log ensures crash recovery without data loss for mutations.", "importance": 0.5, "type": "semantic"},
        {"content": "Hot-cold data separation: recent memories in Redis, older in Qdrant only.", "importance": 0.4, "type": "semantic"},
        {"content": "Request timeout set to 30s to prevent slow LLM responses from blocking threads.", "importance": 0.5, "type": "semantic"},
    ],
    "data-eng": [
        {"content": "ETL pipeline extracts daily audit logs to Postgres for trend analysis.", "importance": 0.5, "type": "semantic"},
        {"content": "Qdrant collection backup exported as snapshot file for disaster recovery.", "importance": 0.6, "type": "semantic"},
        {"content": "Neo4j dump creates full graph backup compatible with neo4j-admin load.", "importance": 0.5, "type": "semantic"},
        {"content": "JSONL format used for memory export to enable streaming and line-by-line processing.", "importance": 0.4, "type": "semantic"},
        {"content": "Data retention policy: ephemeral memories purged after 30 days of low importance.", "importance": 0.5, "type": "semantic"},
        {"content": "Schema migrations tracked via version table in Postgres for idempotent upgrades.", "importance": 0.5, "type": "semantic"},
        {"content": "Embedding model version stored with each vector to detect model change drift.", "importance": 0.6, "type": "semantic"},
        {"content": "Content hash index enables O(1) duplicate detection during memory storage.", "importance": 0.5, "type": "semantic"},
        {"content": "Metrics snapshot captures system state every hour for historical trending.", "importance": 0.4, "type": "semantic"},
        {"content": "Cross-store reconciliation detects Qdrant/Neo4j/Redis synchronization gaps.", "importance": 0.6, "type": "semantic"},
        {"content": "Batch import endpoint accepts JSONL and processes memories with rate limiting.", "importance": 0.4, "type": "semantic"},
        {"content": "Domain statistics materialized in Redis with 5-minute TTL for dashboard.", "importance": 0.4, "type": "semantic"},
        {"content": "Audit log partitioned by month in Postgres for efficient historical queries.", "importance": 0.5, "type": "semantic"},
        {"content": "Memory importance histogram computed hourly for health dashboard display.", "importance": 0.4, "type": "semantic"},
        {"content": "Graph edge strength values normalized to 0.0-1.0 range for consistent scoring.", "importance": 0.4, "type": "semantic"},
        {"content": "Feedback training data requires minimum 30 samples for reranker model training.", "importance": 0.5, "type": "semantic"},
        {"content": "StandardScaler parameters baked into reranker weights for sklearn-free inference.", "importance": 0.5, "type": "semantic"},
        {"content": "Cross-validation uses 3 folds for small datasets and 5 folds for larger ones.", "importance": 0.4, "type": "semantic"},
        {"content": "Training data collected from audit_log feedback entries with enriched features.", "importance": 0.5, "type": "semantic"},
        {"content": "Feature vector includes importance, stability, confidence, recency, and graph distance.", "importance": 0.5, "type": "semantic"},
        {"content": "Sigmoid function used for pure-math inference without sklearn at runtime.", "importance": 0.4, "type": "semantic"},
        {"content": "Redis key recall:ml:reranker_weights stores serialized model parameters.", "importance": 0.4, "type": "semantic"},
        {"content": "Data lineage tracked from raw observation through signal to stored memory.", "importance": 0.5, "type": "semantic"},
        {"content": "Incremental re-embedding runs nightly for memories missing updated vectors.", "importance": 0.4, "type": "semantic"},
        {"content": "Quality metrics: precision, recall, MRR computed from ground-truth test set.", "importance": 0.5, "type": "semantic"},
    ],
}

# 40 search queries covering all domains
SEARCH_QUERIES = [
    # infra
    "Proxmox backup schedule configuration",
    "Docker host resource allocation",
    "VPN routing for media stack",
    "UPS battery backup runtime",
    "ZFS mirror boot drive setup",
    # code-patterns
    "structlog logging configuration",
    "FastAPI dependency injection authentication",
    "Pydantic validation patterns",
    "database singleton factory pattern",
    "Cypher query parameter safety",
    # debug-notes
    "Qdrant wrong input UUID error",
    "Neo4j container startup timeout",
    "Ollama JSON format empty response",
    "SSE test hanging httpx stream",
    "Python output buffering fix",
    # architecture
    "retrieval pipeline stages overview",
    "memory importance decay curve",
    "ML reranker feature extraction",
    "graph spreading activation search",
    "document ingestion pipeline",
    # devops
    "Docker Compose restart deployment",
    "volume mount code changes",
    "container health check configuration",
    "multi-stage Dockerfile optimization",
    "CI pipeline pytest Docker build",
    # security
    "API key authentication bcrypt",
    "CORS origin configuration",
    "rate limiting brute force prevention",
    "input validation SQL injection",
    "TLS certificate management",
    # performance
    "Qdrant HNSW search latency",
    "Redis caching hit rate",
    "connection pool sizing",
    "batch embedding optimization",
    "concurrent LLM call semaphore",
    # data-eng
    "audit log export analysis",
    "Qdrant snapshot backup restore",
    "JSONL memory export format",
    "reranker training data collection",
    "cross-store reconciliation sync",
]

# 20 conversation pairs for session worker (role, content)
CONVERSATIONS = [
    {
        "task": "Debugging Redis connection",
        "turns": [
            ("user", "Redis is refusing connections on port 6379. The API container can't reach it."),
            ("assistant", "Let me check the Docker network. The containers need to be on the same network."),
            ("user", "docker network inspect shows them on different networks."),
            ("assistant", "That's the issue. Add both containers to the same Docker network in compose."),
        ],
    },
    {
        "task": "Setting up Qdrant indexes",
        "turns": [
            ("user", "Search by domain is slow. We're scanning all vectors every time."),
            ("assistant", "We need a payload index on the domain field. Qdrant supports keyword indexes."),
            ("user", "How do I create one?"),
            ("assistant", "Use create_payload_index with field_name='domain', field_schema='keyword'."),
        ],
    },
    {
        "task": "Configuring Neo4j authentication",
        "turns": [
            ("user", "Neo4j is rejecting our connection with 'unauthorized' error."),
            ("assistant", "Check the NEO4J_AUTH environment variable. It should be neo4j/your_password."),
            ("user", "It was set but the password had special characters that weren't escaped."),
            ("assistant", "URL-encode special characters in the connection URI, or use separate user/pass params."),
        ],
    },
    {
        "task": "Optimizing Ollama inference",
        "turns": [
            ("user", "Ollama embeddings are taking 2 seconds per call. That's too slow."),
            ("assistant", "Are you batching the calls? Single-item calls have high overhead per request."),
            ("user", "No, sending one text at a time. Can I batch them?"),
            ("assistant", "Yes, the /api/embed endpoint accepts a list of prompts. Batch 10-20 at a time."),
        ],
    },
    {
        "task": "Implementing memory feedback",
        "turns": [
            ("user", "How should we track which memories were useful during a session?"),
            ("assistant", "Track injected memory IDs, then compare with assistant responses at session end."),
            ("user", "What similarity threshold should we use?"),
            ("assistant", "0.35 cosine similarity works well. Above that, the memory influenced the response."),
        ],
    },
    {
        "task": "Setting up decay worker",
        "turns": [
            ("user", "Memories should lose importance over time if they're not accessed."),
            ("assistant", "Implement a decay worker that runs on a cron schedule, applying logarithmic decay."),
            ("user", "What about pinned memories?"),
            ("assistant", "Pinned memories skip decay entirely. Durable memories decay at 0.15x the normal rate."),
        ],
    },
    {
        "task": "Dashboard SSE events",
        "turns": [
            ("user", "The dashboard needs real-time updates when memories are stored."),
            ("assistant", "Use Server-Sent Events. The API pushes events on memory mutations."),
            ("user", "What about reconnection when the connection drops?"),
            ("assistant", "Use a recursive connect() function with mountedRef to prevent leaks on unmount."),
        ],
    },
    {
        "task": "Consolidation strategy",
        "turns": [
            ("user", "We have too many near-duplicate memories about the same topics."),
            ("assistant", "Consolidation clusters similar memories and merges them with LLM summarization."),
            ("user", "How do we prevent merging memories that are similar but distinct?"),
            ("assistant", "Set min_cluster_size to 3 and use a high similarity threshold of 0.85."),
        ],
    },
    {
        "task": "Signal detection tuning",
        "turns": [
            ("user", "The signal detector is creating too many low-quality memories."),
            ("assistant", "We should separate high-confidence auto-store from medium-confidence pending review."),
            ("user", "What threshold for auto-store vs pending?"),
            ("assistant", "Auto-store at confidence >= 0.8. Below that, queue for human review via signals."),
        ],
    },
    {
        "task": "Graph relationship management",
        "turns": [
            ("user", "Related memories should be connected in the graph for better retrieval."),
            ("assistant", "The auto-linker searches for semantically similar memories and creates RELATED_TO edges."),
            ("user", "What similarity threshold for auto-linking?"),
            ("assistant", "0.5 threshold for RELATED_TO edges. Top 3 similar memories per new memory."),
        ],
    },
    {
        "task": "Backup and restore procedures",
        "turns": [
            ("user", "We need a disaster recovery plan for all the memory data."),
            ("assistant", "Three systems need backup: Qdrant snapshots, Neo4j dump, and Postgres pg_dump."),
            ("user", "What about the JSONL export?"),
            ("assistant", "JSONL export covers Qdrant data but not graph relationships. Use all three backups."),
        ],
    },
    {
        "task": "Multi-user isolation",
        "turns": [
            ("user", "Different users should be able to see who stored each memory."),
            ("assistant", "User attribution stores user_id and username in Qdrant payload and Neo4j node."),
            ("user", "Should memories be private per user?"),
            ("assistant", "Shared visibility: all users see all memories, but can filter by stored_by username."),
        ],
    },
    {
        "task": "Anti-pattern detection",
        "turns": [
            ("user", "We keep making the same mistakes. Can we warn about known anti-patterns?"),
            ("assistant", "Store anti-patterns in a separate Qdrant collection and check during retrieval."),
            ("user", "How does the check work?"),
            ("assistant", "Stage 4.5 in retrieval: search anti-patterns, if similarity > threshold, boost warning score."),
        ],
    },
    {
        "task": "Performance profiling",
        "turns": [
            ("user", "Search latency spikes during consolidation runs. How do we fix this?"),
            ("assistant", "Consolidation does many Qdrant searches. Use scroll_all() for iteration instead."),
            ("user", "We're also hitting Ollama hard during consolidation."),
            ("assistant", "Add a semaphore to limit concurrent Ollama calls and add delay between batches."),
        ],
    },
    {
        "task": "Durability tier assignment",
        "turns": [
            ("user", "Some memories should never decay, like infrastructure facts."),
            ("assistant", "Assign durability=permanent for critical facts, durable for important ones."),
            ("user", "How does this interact with the decay worker?"),
            ("assistant", "Permanent memories are immune to decay. Durable memories decay at 0.15x normal rate."),
        ],
    },
    {
        "task": "Embedding model selection",
        "turns": [
            ("user", "Should we switch from qwen3-embedding to a different model?"),
            ("assistant", "qwen3-embedding:0.6b is lightweight and runs fast. The 1024-dim vectors are good quality."),
            ("user", "What about multilingual support?"),
            ("assistant", "qwen3-embedding handles English well. For multilingual, consider bge-m3 but it's heavier."),
        ],
    },
    {
        "task": "Rate limit configuration",
        "turns": [
            ("user", "The API is getting hammered by the signal detection worker. We need limits."),
            ("assistant", "slowapi with per-endpoint rate limits. Search: 30/min, admin: 10/min, default: 60/min."),
            ("user", "What about the ingest endpoints?"),
            ("assistant", "Ingest at 20/min to prevent Ollama saturation from too many concurrent signals."),
        ],
    },
    {
        "task": "Testing strategy discussion",
        "turns": [
            ("user", "How should we organize the test suite for Recall?"),
            ("assistant", "Three tiers: unit tests (fast, mocked), integration tests (live services), simulation (long-running)."),
            ("user", "What's the split?"),
            ("assistant", "~70 unit tests, ~160 fast integration, ~40 slow LLM tests, plus simulation suites."),
        ],
    },
    {
        "task": "Domain normalization setup",
        "turns": [
            ("user", "We have memories scattered across 'infra', 'infrastructure', 'homelab-infra'."),
            ("assistant", "Domain normalization maps aliases to canonical domains. Define CANONICAL_DOMAINS list."),
            ("user", "How do we migrate existing memories?"),
            ("assistant", "Admin endpoint POST /admin/domains/normalize scans all memories and updates domains."),
        ],
    },
    {
        "task": "Reranker training pipeline",
        "turns": [
            ("user", "How does the ML reranker get trained?"),
            ("assistant", "collect_training_data() pulls from Postgres audit_log feedback entries with features."),
            ("user", "What features does it use?"),
            ("assistant", "11 features: importance, stability, confidence, access_count, recency, pinned, durability, similarity, graph_distance, plus domain and memory_type encoded."),
        ],
    },
]
